### ISSUE TITLE
Focus search when typing

### ISSUE THREAD

**Issue by danirabbit** [elementary/iconbrowser#15]
### Problem

If I start typing without search focused nothing happens

### Proposal

Forward keypress events into the search entry

**Comment by alainm23** [comment]
I have a [small example](https://github.com/alainm23/planify/blob/master/src/Dialogs/QuickFind/QuickFind.vala#L160) of this functionality in Planify, it could be a base.

**Comment by danirabbit** [comment]
These days you can set a capture widget in one line https://valadoc.org/gtk4/Gtk.SearchEntry.set_key_capture_widget.html
